# This is a basic workflow to help you get started with Actions

name: CD Deploy

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: compile
        run: |
          cd user-service
          mvn compile
      - name: test
        run: |
          cd user-service
          mvn test
          
      - name: configure-docker-cli
        env:
          DOCKER_CA: ${{ secrets.DOCKER_CA }}
          DOCKER_CERT: ${{ secrets.DOCKER_CERT }}
          DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
          DOCKER_HOST: "tcp://ec2-18-179-25-169.ap-northeast-1.compute.amazonaws.com:2376"
          DOCKER_TLS_VERIFY: "1"
        run: |
          mkdir -pv ~/.docker
          
          echo "$DOCKER_CA" | base64 --decode > ~/.docker/ca.pem
          echo "$DOCKER_CERT" | base64 --decode > ~/.docker/cert.pem
          echo "$DOCKER_KEY" | base64 --decode > ~/.docker/key.pem
          docker version

          docker version
          
      - name: build-and-deploy
        env:
          DOCKER_HOST: "tcp://ec2-18-179-25-169.ap-northeast-1.compute.amazonaws.com:2376"
          DOCKER_TLS_VERIFY: "1"
        run: |
          make