# This is a basic workflow to help you get started with Actions

name: PR Checker

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: CI action
        run: |
          echo "Hello"
